### ISSUE TITLE
Question about  "loopFindNearKeyframesCloud(cureKeyframeCloud, _curr_kf_idx, 0, _loop_kf_idx) ？

### ISSUE THREAD

**Issue by Tina1994** [gisbi-kim/SC-A-LOAM#11]
Hi, thanks for your contribution. 
I have same question same as the question [https://github.com/gisbi-kim/SC-A-LOAM/issues/7](url)
However, I think the code still have something wrong, the code in the repo is as：

```
 void loopFindNearKeyframesCloud( pcl::PointCloud<PointType>::Ptr& nearKeyframes, const int& key, const int& submap_size, const int& root_idx)
{
    // extract and stacking near keyframes (in global coord)
    nearKeyframes->clear();
    for (int i = -submap_size; i <= submap_size; ++i) {
        int keyNear = key + i; 
        if (keyNear < 0 || keyNear >= int(keyframeLaserClouds.size()) )
            continue;

        mKF.lock(); 
        *nearKeyframes += * local2global(keyframeLaserClouds[keyNear], keyframePosesUpdated[root_idx]);
        mKF.unlock(); 
    }
    if (nearKeyframes->empty())
        return;
    pcl::PointCloud<PointType>::Ptr cloud_temp(new pcl::PointCloud<PointType>());
    downSizeFilterICP.setInputCloud(nearKeyframes);
    downSizeFilterICP.filter(*cloud_temp);
    *nearKeyframes = *cloud_temp;
} // loopFindNearKeyframesCloud
```
where *nearKeyframes += * local2global(keyframeLaserClouds[keyNear], keyframePosesUpdated[root_idx]) should be：
```
*nearKeyframes += * local2global(keyframeLaserClouds[keyNear], keyframePosesUpdated[keyNear]);
```

The target of the function  “loopFindNearKeyframesCloud ” is transforming the nearby keyframe  point cloud stored in keyframeLaserClouds from thr Lidar coordinate to the world coordinate, to form a submap in _loop_kf_idx， so I think local2global should be the tranformation stored in keyframePosesUpdated[keyNear]. 

![微信图片_20220309111635](https://user-images.githubusercontent.com/28301047/157366413-590fe5e6-5fa2-4741-bdf5-338e795b230c.jpg)

**Comment by harveybia** [comment]
Can confirm this is correct.

**Comment by Tina1994** [comment]
> Can confirm this is correct.

Thanks for you reply, are you mean my explain is correct? I am a beginner, so if you mean  the source code is correct, please explain the reason. Thanks again.

**Comment by harveybia** [comment]
Sorry for not being clear, you are correct. The keyframes need to be transformed into the same global frame.
`*nearKeyframes += * local2global(keyframeLaserClouds[keyNear], keyframePosesUpdated[keyNear]);`

> Thanks for you reply, are you mean my explain is correct? I am a beginner, so if you mean the source code is correct, please explain the reason. Thanks again.

**Comment by Tina1994** [comment]
> Sorry for not being clear, you are correct. The keyframes need to be transformed into the same global frame. `*nearKeyframes += * local2global(keyframeLaserClouds[keyNear], keyframePosesUpdated[keyNear]);`
> 
> > Thanks for you reply, are you mean my explain is correct? I am a beginner, so if you mean the source code is correct, please explain the reason. Thanks again.

Thanks you very much! I 'll modify the error in downloaded source code and close this question.
