### ISSUE TITLE
loop closure problem

### ISSUE THREAD

**Issue by mertyavuz41** [gisbi-kim/SC-A-LOAM#17]
Hi there,

I am trying to generate a map which has big loop about 7-8 km, but loop is not closing so I investigated the code and I saw a line that prepare GPS noise error (https://github.com/gisbi-kim/SC-A-LOAM/blob/321cb4b07b7815c114237ce5d87014d2e46b972c/src/laserPosegraphOptimization.cpp#L301)  here. I decreased the error value to 2 meter xy, 1 meter height. But this action was not solve the problem.

Also a few line below there is a comment 'https://github.com/gisbi-kim/SC-A-LOAM/blob/321cb4b07b7815c114237ce5d87014d2e46b972c/src/laserPosegraphOptimization.cpp#L304' like that. So current GPS usage only includes for height correction, to solve the loop closure problem I think that I have to use GPS more effectively for xy dimensions.

Do you have any suggestion to me?

Thanks...
![loop](https://user-images.githubusercontent.com/73120336/183418657-f46b7e72-7a67-4206-938a-79873f017818.png)

**Comment by gitouni** [comment]
I think this setting means GTSAM does not use the XY information of GPS to establish GPS `Prior` Factor, since the Noise Variance is the reciprocal of the Factor weight.
